# Generated by Django 3.0.2 on 2020-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='foobar', max_length=50)),
                ('where', models.CharField(default='foobar', max_length=50)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
