# Generated by Django 3.0.2 on 2020-02-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='images/Blank.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='room',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='where',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
